### ISSUE TITLE
API Inconsistency: String vs URL

### ISSUE THREAD

**Issue by michalciurus** [blockstack/blockstack-ios#14]
```
open func signIn(redirectURI: String,
                     appDomain: URL,
                     manifestURI: URL? = nil,
                     scopes: Array<String> = ["store_write"],
                     completion: ((AuthResult) -> Void)?) {
```

There's a small inconsistency in the API: `redirectURI` is a `String` and `manifestURI` is a `URL`.

It confused me a little when I was implementing the support for Objective-C

**Comment by shreyasthiagaraj** [comment]
Taken care of in 2582f72a7a6761c9ded9bbe2e1bff2281a3607a7 :)
