### ISSUE TITLE
Change the way the bundle is located in code

### ISSUE THREAD

**Issue by michalciurus** [blockstack/blockstack-ios#15]
Currently the bundle is located by:

```
let bundleURL = frameworkBundle.resourceURL?.appendingPathComponent("Blockstack.bundle")
```

It works fine when using Cocoapods, but some users may want to drag & drop the code to their codebase. Then the code will crash.

It happened to me when I was drag & dropping code to a React-Native app - I didn't want to use Cocoapods.

I suggest something much simpler:

```
Bundle(for: type(of: self))
```

This will always succeed, regardless of the setup.

**Comment by shreyasthiagaraj** [comment]
This doesn't work, resource bundle is not found using the method you suggested. Thanks anyways :)
