### ISSUE TITLE
API Inconsistency: `getFile` vs `putFile`

### ISSUE THREAD

**Issue by michalciurus** [blockstack/blockstack-ios#16]
Put file accepts `Dictionary<String, String>` but `getFile` returns `Any?` in completion - shouldn't it also return `Dictionary<String, String>`?

**Comment by michalciurus** [comment]
Moreover: `Dictionary<String, String>` should be a specialization of `getFile` and `putFile`. Generally it should operate on `Data` - just like the web API.

**Comment by shreyasthiagaraj** [comment]
Agreed, will take a look.
