### ISSUE TITLE
`signIn` completion is called on different queues depending on the result

### ISSUE THREAD

**Issue by michalciurus** [blockstack/blockstack-ios#17]
I made a PR to remove dispatching in the ViewController example app to main queue. I did that because I tested it and it worked fine. What I did not test was `success`!

In case of `cancelled` and `failed` the `signIn` completion is called on the main queue. In case of `success` it's called on background queue - that's because `dataTask` operates on a [background queue](https://stackoverflow.com/questions/31746229/does-nsurlsession-for-http-data-task-nsurlsessiondatatask-runs-in-background-t).

My opinion is that all callbacks should be called on the main queue to prevent user errors and keep consistency.

**Comment by shreyasthiagaraj** [comment]
This has (finally) been resolved and committed :). Thanks!
