### ISSUE TITLE
API inconsistency: Callback parameters type

### ISSUE THREAD

**Issue by michalciurus** [blockstack/blockstack-ios#19]
`signIn` uses modern/Swifty `authResult` enum with associated types. `putFile` and `getFile` use one parameter + error type separately.

One generic Result enum could be used across the API:

```
public enum Result<T> {
    case success(T)
    case error
}
```

**Comment by shreyasthiagaraj** [comment]
The current implementation allows easy compatibility with Objective-C. For now I think it's fine. Thanks for the suggestion!
