### ISSUE TITLE
Restore Blockstack ID via Secret Recovery Key

### ISSUE THREAD

**Issue by alvesjtiago** [blockstack/blockstack-ios#23]
When trying to recover my blockstack ID through the Secret Recovery Key, I always get "Incorrect code or password". I'm pretty sure this is the correct one since on the laptop I’m able to export the backup keychain using this password.
Happy to provide any other info about this and help debug the issue. Thank you!

![simulator screen shot - iphone 8 plus - 2018-06-02 at 10 37 09](https://user-images.githubusercontent.com/407470/40869729-4fc1dd14-6652-11e8-8e2d-8d243c77a7b0.png)

**Comment by yknl** [comment]
hey @alvesjtiago are you able to restore this ID using the same code and password anywhere else?

**Comment by alvesjtiago** [comment]
Hi @yknl, yes I am. Just tried it on Chrome and it worked.

**Comment by yknl** [comment]
hey @alvesjtiago, when did you create this ID? Does the secret recovery key look like it's base64 encoded or hex? We changed the encoding of the secret recovery key last week, the onboarding flow now expects it to be base64 encoded.

**Comment by alvesjtiago** [comment]
@yknl it was quite some time ago. I only have the backup keychain phrase from that registration.

I've tested registering a new one and restoring it through the Recovery Key and it works fine. So my question is: for older id's how does one restore it? Writing the 24 word backup keychain phrase does not work like in the desktop. Thank you!

**Comment by yknl** [comment]
@alvesjtiago you can restore using the 12/24 word backup phrase here as well. It should be asking you for a new password if you do.

**Comment by oluapocram** [comment]
Also experiencing this issue. Have a 24-word backup and unable to restore using the Blockstack Browser. 

- OS X Sierra 10.13.4 (17E202) 
- Chrome 67.0.3396.79 (64-bit) 
- Blockstack-for-macOS-v0.29.1.dmg. 

Looks like #1448 fixes the issue.
