### ISSUE TITLE
Add functionality to reset browser state in the SFAuthenticationSession

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-ios#25]
Currently, authentication is done by loading https://browser.blockstack.org inside `SFAuthenticationSession`. If something goes wrong and the browser state gets messed up, there's no way to reset it on device. (It can be done on the simulator but not on a real device.) 

This probably involves a change on the Blockstack browser side as well.

**Comment by shreyasthiagaraj** [comment]
This issue results in #28 for user.

**Comment by shreyasthiagaraj** [comment]
Fixed in **develop**, pending merge to master.
