### ISSUE TITLE
Create an Xcode project for Blockstack SDK

### ISSUE THREAD

**Issue by michalciurus** [blockstack/blockstack-ios#3]
I wanted to create unit tests for the Blockstack SDK but currently there's no sensible way to do that as the SDK doesn't have an Xcode project. Putting the code in a project will enable writing tests and running them on a CI in the future.

Does that sounds like a good idea?

**Comment by yknl** [comment]
Not sure if that's the right way to go about it. The Cocoapods way seems to be to add the tests to the Example project. https://github.com/CocoaPods/CocoaPods/issues/4755

**Comment by michalciurus** [comment]
Ooh, that's very cool, I didn't know that, I felt I missed something! Thanks!
