### ISSUE TITLE
Set up CircleCI continuous testing

### ISSUE THREAD

**Issue by shreyasthiagaraj** [blockstack/blockstack-ios#35]
This will automatically run all unit and UI tests as the master branch is updated.

**Comment by larrysalibra** [comment]
Note: this should work on all repos and not just on master.

I can't help with this either because I don't have admin on this repo.

**Comment by shreyasthiagaraj** [comment]
@larrysalibra this does work on all repos--the circleCI dashboard shows tests being run for commits on any branch. Its just that not all branches have the right config.yml file. That one is in *develop* right now, will be merged into master with the rest of the updates for 0.2.0.

**Comment by shreyasthiagaraj** [comment]
Resolved with 6803e48
