### ISSUE TITLE
Scopes parameters

### ISSUE THREAD

**Issue by alvesjtiago** [blockstack/blockstack-ios#47]
While trying to change scopes I realised that the `signIn` call on https://github.com/blockstack/blockstack-ios/blob/31ddeaa72d4518e3227bae59378d40cb542fba76/Blockstack/Classes/Blockstack.swift#L30 does not pass the scope parameters to https://github.com/blockstack/blockstack-ios/blob/31ddeaa72d4518e3227bae59378d40cb542fba76/Blockstack/Classes/Blockstack.swift#L51 

Should it be added to the call? Happy to make the changes and submit a PR.

**Comment by shreyasthiagaraj** [comment]
Thanks for reporting! Fix is out and will be merged in soon!
