### ISSUE TITLE
iOS profile settings not properly cleared when user signs out

### ISSUE THREAD

**Issue by shreyasthiagaraj** [blockstack/blockstack-ios#50]
This is because "UserDefaults.standard.set(nil, forKey: key)" doesn't actually clear that key.

**Comment by petec029** [comment]
I am unable to sign out of the example iOS app.  Not sure if this is directly related to this issue or a new issue but when I click the sign out button I go to browser.blockstack.org and just get the animated Blockstack logo.  I am running this in the Xcode simulator on my MacBook Pro.
 
![simulator screen shot - iphone 8 - 2018-08-22 at 08 32 26](https://user-images.githubusercontent.com/519271/44463894-2d400980-a5e7-11e8-94b7-52077bff2c19.png)

**Comment by shreyasthiagaraj** [comment]
@petec029 It seems there's a bug with that page now. Tracked here: https://github.com/blockstack/blockstack-browser/issues/1632

For now, try switching to the `multiplayer-support` branch as I made some modifications to sign out on there.
