### ISSUE TITLE
CircleCI tests failing

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-ios#73]
CircleCI tests are failing - it appears to be some problem with CryptoSwift.

**Comment by shreyasthiagaraj** [comment]
Some of the failures have now been fixed by updating CircleCi to the latest version of Xcode (10.2.1)  and a higher version of iPhone. The remaining issue is the failing instagram test, for which the Blockstack.js code will need to be updated in the iOS codebase.

**Comment by shreyasthiagaraj** [comment]
Fixed with ca5b905 and afcfb72e1d4a662542c60e98f3a1563357f2ae83
