### ISSUE TITLE
Bug: iOS13 ASWebAuthenticationSession, no provided presentation context

### ISSUE THREAD

**Issue by dangdennis** [blockstack/blockstack-ios#85]
### Solution

Your previous commit at d7779b387fa11baa738c6a3d7f90d2ec21abcd6e is actually working for me now when I updated my local podfile with your reverted changes. Perhaps a test has to be updated. Thanks for the quality work!

### Issue
Hi @shreyasthiagaraj , I tried to integrate this SDK into iOS13 + SwiftUI, but am receiving the following __error__ when I call `Blockstack.shared.signIn`. I see that you've attempted a fix at commit d7779b387fa11baa738c6a3d7f90d2ec21abcd6e

#### Error 
`
Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=2 "Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start." UserInfo={NSDebugDescription=Cannot start ASWebAuthenticationSession without providing presentation context. Set presentationContextProvider before calling -start.}
`

### Steps to reproduce
1. Create a new SwiftUI project
2. Copy the `Blockstack.shared.signIn` snippet into a Button.
3. Build and click button.

This is my first foray into iOS development, so I'm unable to test a UIKit implementation in iOS13.

### Code snippet
```
import Blockstack
import SwiftUI

struct ContentView: View {
    var body: some View {
        NavigationView {
            VStack {
                Text("Hello World")
                Button("Login with Blockstack") {
                    Blockstack.shared.signIn(
                        redirectURI: URL(string:"https://boto-staging.netlify.com/redirect/")!,
                        appDomain: URL(string: "https://boto-staging.netlify.com")!,
                        manifestURI: nil,
                        scopes: [.storeWrite, .publishData]) { authResult in
                            switch authResult {
                            case .success(let userData):
                                print("sign in success")
                                print("userData=\(userData)")
                            case .cancelled:
                                print("sign in cancelled")
                            case .failed(let error):
                                print("sign in failed")
                                print(error!)
                            }
                    }
                }
            }
            .navigationBarTitle("Home")
        }
        
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
```

### Resources or solutions I've found/tried
1. https://www.reddit.com/r/iOSProgramming/comments/cay92l/update_aswebauthenticationsession_and_swiftui/

**Comment by dangdennis** [comment]
Although resolved on my end, I'll leave this issue open for you to comment and close as necessary.

**Comment by shreyasthiagaraj** [comment]
@dangdennis Did you use the fix I reverted in d7779b3?

**Comment by botoberich** [comment]
I did use that fix. Although I am noticing that I can get into an error state when the auth is unable to “get information about the app.” 

Auth response returns null on my redirect page.

Not sure what causes that yet.

**Comment by dangdennis** [comment]
I did use that fix. Although I am noticing that I can get into an error state when the auth is unable to “get information about the app.” 

Auth response returns null on my redirect page.

Not sure what causes that yet.

**Comment by shreyasthiagaraj** [comment]
@dangdennis Got it. Looking to see if I can reproduce that issue.
