### ISSUE TITLE
iOS 13.2 support when?

### ISSUE THREAD

**Issue by BeIllegalBeagle** [blockstack/blockstack-ios#89]
Some strange things are happening for me using the Blockstack library with the current version of iOS such as signing in multiple times in the same sign-in request and the usage of the `list files` function out right crashing every app that uses it on iOS 13.2.

It seems that might have something to do with the JS bridge? 
![Screenshot 2019-11-09 at 01 00 09](https://user-images.githubusercontent.com/38043915/68519979-5e5c3680-028c-11ea-9c02-e8c61cdda178.png)

**Comment by shreyasthiagaraj** [comment]
Hey, could you check the console to see if there's a more specific error being received?

Also, could you try doing a clean-build? If you are on our slack, I could help solve this faster by chatting with you on there. If not, you can join here:
https://community.blockstack.org/slack

Thanks!

**Comment by shreyasthiagaraj** [comment]
Hey! I just built a new objective-c application as well as a swift application using the latest Xcode, Blockstack pod, and iOS 13.2. The `list files` method worked in both cases.

**Comment by shreyasthiagaraj** [comment]
Closing as there is no response.
